//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public int Id { get; set; }
        public string Repetitions { get; set; }
        public System.DateTime FinishTime { get; set; }
        public string Weight { get; set; }
        public System.DateTime StartTime { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
