// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotNetCoreRepository2.Models;

public partial class Excercises
{
    public int Id { get; set; }

    public string Name { get; set; }
}