// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DotNetCoreRepository2.Models;

public partial class MyWorkoutContext : DbContext
{
    public MyWorkoutContext()
    {

    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Data Source=corsair;Initial Catalog=MyWorkout;Integrated Security=True;Trusted_Connection=True;TrustServerCertificate=True");
    }

    public MyWorkoutContext(DbContextOptions<MyWorkoutContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Excercises> Excercises { get; set; }

    public virtual DbSet<Persons> Persons { get; set; }

    public virtual DbSet<Sets> Sets { get; set; }

    public virtual DbSet<Workouts> Workouts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Excercises>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Persons>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.LastName).HasMaxLength(50);
        });

        modelBuilder.Entity<Sets>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Finish).HasColumnType("datetime");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Start).HasColumnType("datetime");
        });

        modelBuilder.Entity<Workouts>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Finish).HasColumnType("datetime");
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Start).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}