// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotNetCoreRepository2.Models;

public partial class Sets
{
    public int Id { get; set; }

    public int Repetitions { get; set; }

    public int ExcerciseId { get; set; }

    public DateTime? Start { get; set; }

    public DateTime? Finish { get; set; }

    public int? Weight { get; set; }

    public int? WorkoutId { get; set; }
}