// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DotNetCoreRepository2.Models;

public partial class Workouts
{
    public int Id { get; set; }

    public int? PersonId { get; set; }

    public DateTime? Start { get; set; }

    public DateTime? Finish { get; set; }
}